### ISSUE TITLE
Handle user errors from orchestration api

### ISSUE THREAD

**Issue by ErikZigo** [keboola/app-orchestrator-migrate#6]
Pokud pri migraci orchestrace vrati API orchestratoru HTTP 4XX tak by to melo skoncit User Errorem a predat error message z orchestracniho api.

Ted to konci APP errorem:
```
docker-22cf09803f869cdee63e2f1beef4a1fb
```

**Comment by ondrejhlavacek** [comment]
a další

```
docker-15076e636b4e80357e1b78e7b8a20c51
```

**Comment by kacurez** [comment]
znova: https://keboola.slack.com/archives/C09U3R1J4/p1573555238007200

**Comment by ErikZigo** [comment]
Closing,  moved to Jira https://keboola.atlassian.net/browse/PS-1700
